### ISSUE TITLE
Change in returned Gaia column name

### ISSUE THREAD

**Issue by zoghbi-a** [nasa-fornax/fornax-demo-notebooks#340] opened 2024-09-19 19:15 UTC
In the light_curve_generator.md notebook, this call is failing with `KeyError: 'source_id'`:
```python
df_lc_gaia = gaia_get_lightcurves(sample_table, search_radius=1/3600, verbose=0)
```
The returned column name should be`SOURCE_ID` not `source_id`.

It looks like GAIA changed the names of the columns.

**Comment by bsipocz** [comment] 2024-09-19 20:08
I recall relevant astroquery issues due to server-side changes. I think we have addressed all of these, so it's puzzling why you run into it.

What version of astroquery do you use? Also, have you started from a clean state, e.g. nothing is in the data directory/astroquery cache/etc.?

**Comment by bsipocz** [comment] 2024-09-19 20:13
OK, so this is a duplicate of https://github.com/nasa-fornax/fornax-demo-notebooks/issues/207; and the reason why we have `astroquery>=0.4.8.dev0` in the requirements file of that notebook.

So, please check if you indeed have a recent dev version of astroquery (pip installable with ``--pre``); I'm fairly certain that with a version upgrade this will be resolved.

**Comment by zoghbi-a** [comment] 2024-09-19 20:44
Thanks, this is indeed a duplicate. That issue didn't show up when I did the search before creating the issue.

**Comment by bsipocz** [comment] 2024-09-19 20:57
no worries, I only remembered as it was also reported to astroquery multiple times.

**Closed by bsipocz** 2024-09-19 20:57 UTC
Labels: use case: light curves
